server:
  #端口号 tomcat相关配置
  port: 8088
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
  servlet:
    context-path: /

#spring
spring:
  #应用名称
  application:
    name: yu
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/yu?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
      username: root
      password: 123456
  #redis
  redis:
    #服务器地址
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      #最大连接数量  使用负数无限制
      max-active: 100
      #最大阻塞时间  使用负数无限制
      max-wait: -1
      #最大空闲连接
      max-idle: 500
      #最小空闲连接
      min-idle: 0
      #连接超时时间(毫秒)
      timeout: 1000
    # Redis数据库索引（默认为0）
    database: 0

#mybatis-plus相关配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml